### ISSUE TITLE
API Key option ?

### ISSUE THREAD

**Issue by bigminer** [Checkmarx/ast-teamcity-plugin#150]
Why do we have to enter these values explicitly in the teamcity plugin? I would much rather use the api key option just like I do with the command line. I don't have access to the client id and secret because I am not the admin of our account. I am however able to generate my own api key.

As per your own documentation here.
https://checkmarx.com/resource/documents/en/34965-118315-authentication-for-checkmarx-one-cli.html
The CLI automatically extracts all relevant account info (Base URL, Auth URL, Tenant name) from the API Key. You can use arguments to submit these values explicitly, overriding the extracted values. However, this is generally not recommended.

**Comment by jbrotsos** [comment]
@bigminer the main reason is that the API key is tied to your user account. If your user account was to be deactivated on CxOne, the pipelines will fail.

You also don't need admin role, you just need 'manage-clients' role.

As a workaround, you can use the API key in the Additional Params.

Let me know if you have any follow up questions: james.brotsos@checkmarx.com
